#pragma once
#include "FifamEnum.h"

ENUM_BEGIN(FifamBeg, UInt)
    ENUM_MEMBER(1,         With1stLeg,            L"BEG_WITH_1_LEG")
    ENUM_MEMBER(1,         _1stLeg,               L"BEG_1ST_LEG")
    ENUM_MEMBER(2,         With2ndLeg,            L"BEG_WITH_2_LEG")
    ENUM_MEMBER(2,         _2ndLeg,               L"BEG_2ND_LEG")
    ENUM_MEMBER(4,         WithReplay,            L"BEG_WITH_REPLAY")
    ENUM_MEMBER(8,         WithExtraTime,         L"BEG_WITH_EXTRA_TIME")
    ENUM_MEMBER(16,        WithGoldenGoal,        L"BEG_WITH_GOLDEN_GOAL")
    ENUM_MEMBER(32,        WithPenalty,           L"BEG_WITH_PENALTY")
    ENUM_MEMBER(64,        End,                   L"BEG_END")
    ENUM_MEMBER(256,       _1stPlayed,            L"BEG_1ST_PLAYED")
    ENUM_MEMBER(512,       _2ndPlayed,            L"BEG_2ND_PLAYED")
    ENUM_MEMBER(4096,      ExtraTime,             L"BEG_EXTRA_TIME")
    ENUM_MEMBER(8192,      GoldenGoal,            L"BEG_GOLDEN_GOAL")
    ENUM_MEMBER(16384,     Penalty,               L"BEG_PENALTY")
    ENUM_MEMBER(32768,     Finished,              L"BEG_FINISHED")
    ENUM_MEMBER(67108864,  WithSilverGoal,        L"BEG_WITH_SILVER_GOAL")
    ENUM_MEMBER(134217728, WithoutAwayGoal,       L"BEG_WITHOUT_AWAY_GOAL")
    ENUM_MEMBER(268435456, NoShuffle,             L"BEG_NO_SHUFFLE")
    ENUM_MEMBER(536870912, NoPremierLeagueTeams,  L"BEG_NO_PREMIERLEAGUE_TEAMS")
    ENUM_DEFAULT_READ_WRITE
ENUM_END(FifamBeg)
