#pragma once
#include "FifamTypes.h"
#include "FifamEnum.h"

ENUM_BEGIN(FifamCompType, UChar)
    ENUM_MEMBER( 0, Root,            L"ROOT")
    ENUM_MEMBER( 1, League,          L"LEAGUE")
    ENUM_MEMBER( 2, SpareLeague,     L"SPARE_LEAGUE")
    ENUM_MEMBER( 3, FaCup,           L"FA_CUP")
    ENUM_MEMBER( 4, LeagueCup,       L"LE_CUP")
    ENUM_MEMBER( 5, ChallengeShield, L"CHALLENGE_SHIELD")
    ENUM_MEMBER( 6, ConferenceCup,   L"CONFERENCE_CUP")
    ENUM_MEMBER( 7, SuperCup,        L"SUPERCUP")
    ENUM_MEMBER( 8, Relegation,      L"RELEGATION")
    ENUM_MEMBER( 9, ChampionsLeague, L"CHAMPIONSLEAGUE")
    ENUM_MEMBER(10, UefaCup,         L"UEFA_CUP")
    ENUM_MEMBER(11, Toyota,          L"TOYOTA")
    ENUM_MEMBER(12, EuroSuperCup,    L"EURO_SUPERCUP")
    ENUM_MEMBER(13, WorldClubChamp,  L"WORLD_CLUB_CHAMP")
    ENUM_MEMBER(14, UIC,             L"UIC")
    ENUM_MEMBER(15, QualiWC,         L"QUALI_WC")
    ENUM_MEMBER(16, QualiEC,         L"QUALI_EC")
    ENUM_MEMBER(17, WorldCup,        L"WORLD_CUP")
    ENUM_MEMBER(18, EuroCup,         L"EURO_CUP")
    ENUM_MEMBER(19, Rel1,            L"REL1")
    ENUM_MEMBER(20, Rel2,            L"REL2")
    ENUM_MEMBER(21, Rel3,            L"REL3")
    ENUM_MEMBER(22, Indoor,          L"INDOOR")
    ENUM_MEMBER(23, Friendly,        L"FRIENDLY")
    ENUM_MEMBER(24, Pool,            L"POOL")
    ENUM_MEMBER(25, Unk25,           L"UNKNOWN_25")
    ENUM_MEMBER(26, Unk26,           L"UNKNOWN_26")
    ENUM_MEMBER(27, CustomComp,      L"CUSTOM_COMP")
    ENUM_MEMBER(28, ReserveLeague,   L"RESERVE")
    ENUM_MEMBER(29, FriendlyNationalTeam, L"FRIENDLY_NATIONALTEAM")
    ENUM_MEMBER(30, Promotion,       L"PROMOTION")
    ENUM_MEMBER(31, U20WorldCup,     L"U20_WORLD_CUP")
    ENUM_MEMBER(32, ConfedCup,       L"CONFED_CUP")
    ENUM_MEMBER(33, CopaAmerica,     L"COPA_AMERICA")
    ENUM_MEMBER(35, ICC,             L"ICC")
    ENUM_MEMBER(36, EuroNLQ,         L"Q_EURO_NL")
    ENUM_MEMBER(37, EuroNL,          L"EURO_NL")
    ENUM_MEMBER(38, YouthChampionsLeague, L"YOUTH_CHAMPIONSLEAGUE")
    ENUM_MEMBER(39, Continental1,    L"CONTINENTAL_1")
    ENUM_MEMBER(40, Continental2,    L"CONTINENTAL_2")
    ENUM_MEMBER(41, NamNLQ,          L"Q_NAM_NL")
    ENUM_MEMBER(42, NamNL,           L"NAM_NL")
    ENUM_MEMBER(43, NamCup,          L"NAM_CUP")
    ENUM_MEMBER(44, AfricaCupQ,      L"Q_AFRICA_CUP")
    ENUM_MEMBER(45, AfricaCup,       L"AFRICA_CUP")
    ENUM_MEMBER(46, AsiaCupQ,        L"Q_ASIA_CUP")
    ENUM_MEMBER(47, AsiaCup,         L"ASIA_CUP")
    ENUM_MEMBER(48, OfcCupQ,         L"Q_OFC_CUP")
    ENUM_MEMBER(49, OfcCup,          L"OFC_CUP")
    ENUM_MEMBER(50, U20WCQ,          L"Q_U20_WC")
    ENUM_MEMBER(51, ConferenceLeague, L"CONFERENCE_LEAGUE")
    ENUM_MEMBER(52, Finalissima,     L"FINALISSIMA")
    ENUM_MEMBER(53, U17WCQ,          L"Q_U17_WC")
    ENUM_MEMBER(54, U17WC,           L"U17_WORLD_CUP")
    ENUM_MEMBER(55, U21ECQ,          L"Q_U21_EC")
    ENUM_MEMBER(56, U21EC,           L"U21_EC")
    ENUM_MEMBER(57, U19ECQ,          L"Q_U19_EC")
    ENUM_MEMBER(58, U19EC,           L"U19_EC")
    ENUM_MEMBER(59, U17ECQ,          L"Q_U17_EC")
    ENUM_MEMBER(60, U17EC,           L"U17_EC")
    ENUM_MEMBER(61, OlympicQ,        L"Q_OLYMPIC")
    ENUM_MEMBER(62, Olympic,         L"OLYMPIC")
    ENUM_MEMBER(201, Custom1,        L"CUSTOM_COMP_TYPE_1")
    ENUM_MEMBER(202, Custom2,        L"CUSTOM_COMP_TYPE_2")
    ENUM_MEMBER(203, Custom3,        L"CUSTOM_COMP_TYPE_3")
    ENUM_MEMBER(204, Custom4,        L"CUSTOM_COMP_TYPE_4")
    ENUM_MEMBER(205, Custom5,        L"CUSTOM_COMP_TYPE_5")
    ENUM_MEMBER(206, Custom6,        L"CUSTOM_COMP_TYPE_6")
    ENUM_MEMBER(207, Custom7,        L"CUSTOM_COMP_TYPE_7")
    ENUM_MEMBER(208, Custom8,        L"CUSTOM_COMP_TYPE_8")
    ENUM_MEMBER(209, Custom9,        L"CUSTOM_COMP_TYPE_9")
    ENUM_MEMBER(210, Custom10,       L"CUSTOM_COMP_TYPE_10")
    ENUM_DEFAULT_VALUE(Root)
    ENUM_DEFAULT_READ_WRITE
ENUM_END(FifamCompType)
