#pragma once

#pragma once
#include "FifamTypes.h"
#include "FifamEnum.h"

ENUM_BEGIN(FifamPlayerInjuryType, UInt)
    ENUM_MEMBER(0,   RupturedAchillesTendon,        L"Ruptured Achilles Tendon")
    ENUM_MEMBER(1,   TornAchillesTendon,            L"Torn Achilles Tendon")
    ENUM_MEMBER(2,   InflamedAchillesTendon,        L"Inflamed Achilles Tendon")
    ENUM_MEMBER(3,   ProblemswithAdductor,          L"Problems with Adductor")
    ENUM_MEMBER(4,   StrainedAdductor,              L"Strained Adductor")
    ENUM_MEMBER(5,   StrainedLateralLigaments,      L"Strained Lateral Ligaments")
    ENUM_MEMBER(6,   TornLateralLigaments,          L"Torn Lateral Ligaments")
    ENUM_MEMBER(7,   RupturedLateralLigaments,      L"Ruptured Lateral Ligaments")
    ENUM_MEMBER(8,   StrainedMedialLigaments,       L"Strained Medial Ligaments")
    ENUM_MEMBER(9,   TornMedialLigaments,           L"Torn Medial Ligaments")
    ENUM_MEMBER(10,  RupturedMedialLigaments,       L"Ruptured Medial Ligaments")
    ENUM_MEMBER(11,  BrokenCollarbone,              L"Broken Collarbone")
    ENUM_MEMBER(12,  KneeContusion,                 L"Knee Contusion")
    ENUM_MEMBER(13,  AnkleContusion,                L"Ankle Contusion")
    ENUM_MEMBER(14,  CapsuleTearKnee,               L"Capsule Tear (knee)")
    ENUM_MEMBER(15,  CapsuleTearAnkle,              L"Capsule Tear (ankle)")
    ENUM_MEMBER(16,  FracturedAnkle,                L"Fractured Ankle")
    ENUM_MEMBER(17,  BruisedAnkle,                  L"Bruised Ankle")
    ENUM_MEMBER(18,  TornCruciateLigament,          L"Torn Cruciate Ligament")
    ENUM_MEMBER(19,  RupturedCruciateLigament,      L"Ruptured Cruciate Ligament")
    ENUM_MEMBER(20,  GroinStrain,                   L"Groin Strain")
    ENUM_MEMBER(21,  TornCartilage,                 L"Torn Cartilage")
    ENUM_MEMBER(22,  FracturedMetatarsal,           L"Fractured Metatarsal")
    ENUM_MEMBER(23,  RupturedMuscle,                L"Ruptured Muscle")
    ENUM_MEMBER(24,  Onychia,                       L"Onychia")
    ENUM_MEMBER(25,  MuscleSpasm,                   L"Muscle Spasm")
    ENUM_MEMBER(26,  SyndesmoticLigamentAvulsion,   L"Syndesmotic Ligament Avulsion")
    ENUM_MEMBER(27,  GroinProblems,                 L"Groin Problems")
    ENUM_MEMBER(28,  ThighStrain,                   L"Thigh Strain")
    ENUM_MEMBER(29,  FracturedTibia,                L"Fractured Tibia")
    ENUM_MEMBER(30,  FracturedFibula,               L"Fractured Fibula")
    ENUM_MEMBER(31,  BruisedCalfMuscle,             L"Bruised Calf Muscle")
    ENUM_MEMBER(32,  RotatorCuffCalcificTendonitis, L"Rotator Cuff Calcific Tendonitis")
    ENUM_MEMBER(33,  FracturedToe,                  L"Fractured Toe")
    ENUM_MEMBER(34,  BruisedToe,                    L"Bruised Toe")
    ENUM_MEMBER(35,  BruisedFinger,                 L"Bruised Finger")
    ENUM_MEMBER(36,  FracturedFinger,               L"Fractured Finger")
    ENUM_MEMBER(37,  FracturedHand,                 L"Fractured Hand")
    ENUM_MEMBER(38,  DislocatedShoulder,            L"Dislocated Shoulder")
    ENUM_MEMBER(39,  Concussion,                    L"Concussion")
    ENUM_MEMBER(40,  BrokenNose,                    L"Broken Nose")
    ENUM_MEMBER(41,  BrokenAnkle,                   L"Broken Ankle")
    ENUM_MEMBER(42,  FracturedFoot,                 L"Fractured Foot")
    ENUM_MEMBER(43,  BrokenLowerLeg,                L"Broken Lower Leg")
    ENUM_MEMBER(44,  BrokenThigh,                   L"Broken Thigh")
    ENUM_MEMBER(45,  BrokenToe,                     L"Broken Toe")
    ENUM_MEMBER(46,  BruisedHead,                   L"Bruised Head")
    ENUM_MEMBER(47,  BruisedJaw,                    L"Bruised Jaw")
    ENUM_MEMBER(48,  BruisedRib,                    L"Bruised Rib")
    ENUM_MEMBER(49,  BruisedShin,                   L"Bruised Shin")
    ENUM_MEMBER(50,  BruisedThigh,                  L"Bruised Thigh")
    ENUM_MEMBER(51,  CalfStrain,                    L"Calf Strain")
    ENUM_MEMBER(52,  ChestInjury,                   L"Chest Injury")
    ENUM_MEMBER(53,  Cold,                          L"Cold")
    ENUM_MEMBER(54,  CutHand,                       L"Cut Hand")
    ENUM_MEMBER(55,  DamagedAchillesTendon,         L"Damaged Achilles Tendon")
    ENUM_MEMBER(56,  DamagedElbow,                  L"Damaged Elbow")
    ENUM_MEMBER(57,  DamagedHeel,                   L"Damaged Heel")
    ENUM_MEMBER(58,  DamagedKneeCap,                L"Damaged Knee Cap")
    ENUM_MEMBER(59,  DamagedKneeCartilage,          L"Damaged Knee Cartilage")
    ENUM_MEMBER(60,  DamagedNeck,                   L"Damaged Neck")
    ENUM_MEMBER(61,  DamagedPatellarLigament,       L"Damaged Patellar Ligament")
    ENUM_MEMBER(62,  DamagedShoulder,               L"Damaged Shoulder")
    ENUM_MEMBER(63,  DeadLeg,                       L"Dead Leg")
    ENUM_MEMBER(64,  DislocatedJaw,                 L"Dislocated Jaw")
    ENUM_MEMBER(65,  FacialInjury,                  L"Facial Injury")
    ENUM_MEMBER(66,  Flu,                           L"Flu")
    ENUM_MEMBER(67,  FoodPoisoning,                 L"Food Poisoning")
    ENUM_MEMBER(68,  FracturedArm,                  L"Fractured Arm")
    ENUM_MEMBER(69,  FracturedCheekbone,            L"Fractured Cheekbone")
    ENUM_MEMBER(70,  FracturedJaw,                  L"Fractured Jaw")
    ENUM_MEMBER(71,  FracturedRibs,                 L"Fractured Ribs")
    ENUM_MEMBER(72,  FracturedSkull,                L"Fractured Skull")
    ENUM_MEMBER(73,  FracturedWrist,                L"Fractured Wrist")
    ENUM_MEMBER(74,  GashedHead,                    L"Gashed Head")
    ENUM_MEMBER(75,  GashedLowerLeg,                L"Gashed Lower Leg")
    ENUM_MEMBER(76,  GashedFoot,                    L"Gashed Foot")
    ENUM_MEMBER(77,  GashedUpperLeg,                L"Gashed Upper Leg")
    ENUM_MEMBER(78,  HeelSpur,                      L"Heel Spur")
    ENUM_MEMBER(79,  Hernia,                        L"Hernia")
    ENUM_MEMBER(80,  HipInjury,                     L"Hip Injury")
    ENUM_MEMBER(81,  KneeProblems,                  L"Knee Problems")
    ENUM_MEMBER(82,  LowBackPain,                   L"Low Back Pain")
    ENUM_MEMBER(83,  MuscleProblems,                L"Muscle Problems")
    ENUM_MEMBER(84,  RupturedPatellarLigament,      L"Ruptured Patellar Ligament")
    ENUM_MEMBER(85,  RupturedMuscleFibre,           L"Ruptured Muscle Fibre")
    ENUM_MEMBER(86,  SeriousViralInfection,         L"Serious Viral Infection")
    ENUM_MEMBER(87,  ShinSplints,                   L"Shin Splints")
    ENUM_MEMBER(88,  SlippedDisc,                   L"Slipped Disc")
    ENUM_MEMBER(89,  SprainedAnkle,                 L"Sprained Ankle")
    ENUM_MEMBER(90,  SprainedWrist,                 L"Sprained Wrist")
    ENUM_MEMBER(91,  StrainedAnkleLigaments,        L"Strained Ankle Ligaments")
    ENUM_MEMBER(92,  RotatorCuffInjury,             L"Rotator Cuff Injury")
    ENUM_MEMBER(93,  StrainedNeck,                  L"Strained Neck")
    ENUM_MEMBER(94,  StubbedFinger,                 L"Stubbed Finger")
    ENUM_MEMBER(95,  StubbedToe,                    L"Stubbed Toe")
    ENUM_MEMBER(96,  TornAnkleLigaments,            L"Torn Ankle Ligaments")
    ENUM_MEMBER(97,  TornCalfMuscle,                L"Torn Calf Muscle")
    ENUM_MEMBER(98,  TornGroinMuscle,               L"Torn Groin Muscle")
    ENUM_MEMBER(99,  TornHamstring,                 L"Torn Hamstring")
    ENUM_MEMBER(100, TwistedAnkle,                  L"Twisted Ankle")
    ENUM_MEMBER(101, TwistedKnee,                   L"Twisted Knee")
    ENUM_MEMBER(102, ViralInfection,                L"Viral Infection")
    ENUM_MEMBER(103, AchillesTendonIrritation,      L"Achilles Tendon Irritation")
    ENUM_MEMBER(104, LigamentInjury,                L"Ligament Injury")
    ENUM_MEMBER(105, PulledMuscle,                  L"Pulled Muscle")
    ENUM_MEMBER(106, Bruise,                        L"Bruise")
    ENUM_MEMBER(107, Effusion,                      L"Effusion")
    ENUM_MEMBER(108, TendonInjury,                  L"Tendon Injury")
    ENUM_MEMBER(109, TendonInflammation,            L"Tendon Inflammation")
    ENUM_MEMBER(110, TendonIrritation,              L"Tendon Irritation")
    ENUM_MEMBER(111, DamagedTendon,                 L"Damaged Tendon")
    ENUM_MEMBER(112, RupturedTendon,                L"Ruptured Tendon")
    ENUM_MEMBER(113, Inflammation,                  L"Inflammation")
    ENUM_MEMBER(114, Infection,                     L"Infection")
    ENUM_MEMBER(115, AbdominalInfluenza,            L"Abdominal Influenza")
    ENUM_MEMBER(116, FatigueFracture,               L"Fatigue Fracture ")
    ENUM_MEMBER(117, Laceration,                    L"Laceration")
    ENUM_MEMBER(118, LaceratedWound,                L"Lacerated Wound")
    ENUM_MEMBER(119, Fissure,                       L"Fissure")
    ENUM_MEMBER(120, Onychia2,                      L"Onychia 2")
    ENUM_MEMBER(121, Lumbago,                       L"Lumbago")
    ENUM_MEMBER(122, CapsularRuptureToe,            L"Capsular Rupture (Toe)")
    ENUM_MEMBER(123, CapsularBruiseToe,             L"Capsular Bruise (Toe)")
    ENUM_MEMBER(124, BruisedKnee,                   L"Bruised Knee")
    ENUM_MEMBER(125, BoneStrain,                    L"Bone Strain")
    ENUM_MEMBER(126, PatellaTendonProblems,         L"Patella Tendon Problems")
    ENUM_MEMBER(127, BruisedBack,                   L"Bruised Back")
    ENUM_MEMBER(128, AbdominalMuscleRupture,        L"Abdominal Muscle Rupture")
    ENUM_MEMBER(129, AbdominalMuscleStrain,         L"Abdominal Muscle Strain")
    ENUM_MEMBER(130, ShinboneandFibulaRupture,      L"Shinbone and Fibula Rupture")
    ENUM_MEMBER(131, BrokenShoulder,                L"Broken Shoulder")
    ENUM_MEMBER(132, DamagedSyndesmosis,            L"Damaged Syndesmosis")
    ENUM_MEMBER(133, HerniatedDisk,                 L"Herniated Disk")
    ENUM_MEMBER(134, PlantarisTendonRupture,        L"Plantaris Tendon Rupture")
    ENUM_MEMBER(135, PlantarisTendonInjury,         L"Plantaris Tendon Injury")
    ENUM_MEMBER(136, ThighInjury,                   L"Thigh Injury")
    ENUM_MEMBER(137, CalfInjury,                    L"Calf Injury")
    ENUM_MEMBER(138, PubicBoneInflammation,         L"Pubic Bone Inflammation")
    ENUM_MEMBER(139, FootInjury,                    L"Foot Injury")
    ENUM_MEMBER(140, PeriosteumProblems,            L"Periosteum Problems")
    ENUM_MEMBER(141, ToothProblems,                 L"Tooth Problems")
    ENUM_MEMBER(142, CapsularInjury,                L"Capsular Injury")
    ENUM_MEMBER(143, SynovialBursaInflammation,     L"Synovial Bursa Inflammation")
    ENUM_MEMBER(144, SynovialBursaInjury,           L"Synovial Bursa Injury")
    ENUM_MEMBER(145, PelviceInjury,                 L"Pelvice Injury")
    ENUM_MEMBER(146, OtitisoftheMiddleEar,          L"Otitis of the Middle Ear")
    ENUM_DEFAULT_VALUE(RupturedAchillesTendon)
    ENUM_DEFAULT_READ_WRITE
ENUM_END(FifamPlayerInjuryType)
