#pragma once
#include "FifamTypes.h"
#include "FifamEnum.h"

ENUM_BEGIN(FifamCompType, UChar)
    ENUM_MEMBER( 0, Root,            L"ROOT")
    ENUM_MEMBER( 1, League,          L"LEAGUE")
    ENUM_MEMBER( 2, SpareLeague,     L"SPARE_LEAGUE")
    ENUM_MEMBER( 3, FaCup,           L"FA_CUP")
    ENUM_MEMBER( 4, LeagueCup,       L"LE_CUP")
    ENUM_MEMBER( 5, ChallengeShield, L"CHALLENGE_SHIELD")
    ENUM_MEMBER( 6, ConferenceCup,   L"CONFERENCE_CUP")
    ENUM_MEMBER( 7, SuperCup,        L"SUPERCUP")
    ENUM_MEMBER( 8, Relegation,      L"RELEGATION")
    ENUM_MEMBER( 9, ChampionsLeague, L"CHAMPIONSLEAGUE")
    ENUM_MEMBER(10, UefaCup,         L"UEFA_CUP")
    ENUM_MEMBER(11, Toyota,          L"TOYOTA")
    ENUM_MEMBER(12, EuroSuperCup,    L"EURO_SUPERCUP")
    ENUM_MEMBER(13, WorldClubChamp,  L"WORLD_CLUB_CHAMP")
    ENUM_MEMBER(14, UIC,             L"UIC")
    ENUM_MEMBER(15, QualiWC,         L"QUALI_WC")
    ENUM_MEMBER(16, QualiEC,         L"QUALI_EC")
    ENUM_MEMBER(17, WorldCup,        L"WORLD_CUP")
    ENUM_MEMBER(18, EuroCup,         L"EURO_CUP")
    ENUM_MEMBER(19, Rel1,            L"REL1")
    ENUM_MEMBER(20, Rel2,            L"REL2")
    ENUM_MEMBER(21, Rel3,            L"REL3")
    ENUM_MEMBER(22, Indoor,          L"INDOOR")
    ENUM_MEMBER(23, Friendly,        L"FRIENDLY")
    ENUM_MEMBER(24, Pool,            L"POOL")
    ENUM_MEMBER(25, Unk25,           L"UNKNOWN_25")
    ENUM_MEMBER(26, Unk26,           L"UNKNOWN_26")
    ENUM_MEMBER(27, CustomComp,      L"CUSTOM_COMP")
    ENUM_MEMBER(28, ReserveLeague,   L"RESERVE")
    ENUM_MEMBER(29, FriendlyNationalTeam, L"FRIENDLY_NATIONALTEAM")
    ENUM_MEMBER(30, Promotion,       L"PROMOTION")
    ENUM_MEMBER(31, U20WorldCup,     L"U20_WORLD_CUP")
    ENUM_MEMBER(32, ConfedCup,       L"CONFED_CUP")
    ENUM_MEMBER(33, CopaAmerica,     L"COPA_AMERICA")
    ENUM_DEFAULT_VALUE(Root)
    ENUM_DEFAULT_READ_WRITE
ENUM_END(FifamCompType)
