#pragma once
#include "FifamTypes.h"
#include "FifamEnum.h"
#include "Color.h"

ENUM_BEGIN(FifamClubInterfaceColor04, UChar)
    ENUM_MEMBER(0,  Red                    , L"Red")
    ENUM_MEMBER(1,  RedViolet              , L"RedViolet")
    ENUM_MEMBER(2,  BrightRed              , L"BrightRed")
    ENUM_MEMBER(3,  MidRed                 , L"MidRed")
    ENUM_MEMBER(4,  ReddishYellowPastel    , L"ReddishYellowPastel")
    ENUM_MEMBER(5,  LightGreen             , L"LightGreen")
    ENUM_MEMBER(6,  MidGreen               , L"MidGreen")
    ENUM_MEMBER(7,  GreenPastel            , L"GreenPastel")
    ENUM_MEMBER(8,  LightGreenishBluePastel, L"LightGreenishBluePastel")
    ENUM_MEMBER(9,  Blue                   , L"Blue")
    ENUM_MEMBER(10, DarkBlue               , L"DarkBlue")
    ENUM_MEMBER(11, PaleGrey               , L"PaleGrey")
    ENUM_MEMBER(12, MidBlue                , L"MidBlue")
    ENUM_MEMBER(13, LightBluePastel        , L"LightBluePastel")
    ENUM_MEMBER(14, BluishPurple           , L"BluishPurple")
    ENUM_MEMBER(15, BluePastel             , L"BluePastel")
    ENUM_MEMBER(16, Violet                 , L"Violet")
    ENUM_MEMBER(17, PaleVioletPastel       , L"PaleVioletPastel")
    ENUM_MEMBER(18, Yellow                 , L"Yellow")
    ENUM_MEMBER(19, DarkYellow             , L"DarkYellow")
    ENUM_MEMBER(20, Orange                 , L"Orange")
    ENUM_MEMBER(21, Gold                   , L"Gold")
    ENUM_MEMBER(22, White                  , L"White")
    ENUM_MEMBER(23, Black                  , L"Black")
    ENUM_MEMBER(24, Brown                  , L"Brown")
    ENUM_MEMBER(25, Grey                   , L"Grey")
    ENUM_MEMBER(26, GreyishBlue            , L"GreyishBlue")
    ENUM_DEFAULT_VALUE(White)
ENUM_END(FifamClubInterfaceColor04)

ENUM_BEGIN(FifamClubInterfaceColor07, UChar)
    ENUM_MEMBER(0,  Default,      L"Default")
    ENUM_MEMBER(1,  White_1,      L"White 1")
    ENUM_MEMBER(2,  Black_1,      L"Black 1")
    ENUM_MEMBER(3,  Orange_1,     L"Orange 1")
    ENUM_MEMBER(4,  Yellow_1,     L"Yellow 1")
    ENUM_MEMBER(5,  Red_1,        L"Red 1")
    ENUM_MEMBER(6,  Green_1,      L"Green 1")
    ENUM_MEMBER(7,  Blue_1,       L"Blue 1")
    ENUM_MEMBER(8,  Dark_purple,  L"Dark purple")
    ENUM_MEMBER(9,  Light_blue_2, L"Light blue 2")
    ENUM_MEMBER(10, Brown_1,      L"Brown 1")
    ENUM_MEMBER(11, Pink_1,       L"Pink 1")
    ENUM_MEMBER(12, Dark_red,     L"Dark red")
    ENUM_MEMBER(13, Purple_1,     L"Purple 1")
    ENUM_MEMBER(14, Light_purple, L"Light purple")
    ENUM_MEMBER(15, White_2,      L"White 2")
    ENUM_MEMBER(16, White_3,      L"White 3")
    ENUM_MEMBER(17, Grey,         L"Grey")
    ENUM_MEMBER(18, Ochre,        L"Ochre")
    ENUM_MEMBER(19, Yellow_2,     L"Yellow 2")
    ENUM_MEMBER(20, Lemon,        L"Lemon")
    ENUM_MEMBER(21, Gold_1,       L"Gold 1")
    ENUM_MEMBER(22, Gold_2,       L"Gold 2")
    ENUM_MEMBER(23, Orange_2,     L"Orange 2")
    ENUM_MEMBER(24, Orange_3,     L"Orange 3")
    ENUM_MEMBER(25, Brown_2,      L"Brown 2")
    ENUM_MEMBER(26, Pink_2,       L"Pink 2")
    ENUM_MEMBER(27, Magenta_1,    L"Magenta 1")
    ENUM_MEMBER(28, Magenta_2,    L"Magenta 2")
    ENUM_MEMBER(29, Red_2,        L"Red 2")
    ENUM_MEMBER(30, Red_3,        L"Red 3")
    ENUM_MEMBER(31, Red_4,        L"Red 4")
    ENUM_MEMBER(32, Red_5,        L"Red 5")
    ENUM_MEMBER(33, Red_6,        L"Red 6")
    ENUM_MEMBER(34, Green_2,      L"Green 2")
    ENUM_MEMBER(35, Green_3,      L"Green 3")
    ENUM_MEMBER(36, Green_4,      L"Green 4")
    ENUM_MEMBER(37, Green_5,      L"Green 5")
    ENUM_MEMBER(38, Green_6,      L"Green 6")
    ENUM_MEMBER(39, Green_7,      L"Green 7")
    ENUM_MEMBER(40, Green_8,      L"Green 8")
    ENUM_MEMBER(41, Light_blue_1, L"Light blue 1")
    ENUM_MEMBER(42, Light_blue_4, L"Light blue 4")
    ENUM_MEMBER(43, Light_blue_3, L"Light blue 3")
    ENUM_MEMBER(44, Blue_2,       L"Blue 2")
    ENUM_MEMBER(45, Blue_3,       L"Blue 3")
    ENUM_MEMBER(46, Blue_4,       L"Blue 4")
    ENUM_MEMBER(47, Blue_5,       L"Blue 5")
    ENUM_MEMBER(48, Blue_6,       L"Blue 6")
    ENUM_MEMBER(49, Blue_7,       L"Blue 7")
    ENUM_MEMBER(50, Blue_8,       L"Blue 8")
    ENUM_MEMBER(51, Blue_9,       L"Blue 9")
    ENUM_MEMBER(52, Blue_10,      L"Blue 10")
    ENUM_MEMBER(53, Purple_2,     L"Purple 2")
    ENUM_MEMBER(54, Purple_3,     L"Purple 3")
    ENUM_MEMBER(55, Purple_4,     L"Purple 4")
    ENUM_MEMBER(56, Purple_5,     L"Purple 5")
    ENUM_MEMBER(57, Purple_6,     L"Purple 6")
    ENUM_MEMBER(58, Purple_7,     L"Purple 7")
    ENUM_MEMBER(59, Brown_3,      L"Brown 3")
    ENUM_MEMBER(60, Brown_4,      L"Brown 4")
    ENUM_MEMBER(61, Black_2,      L"Black 2")
    ENUM_MEMBER(62, Black_3,      L"Black 3")
    ENUM_MEMBER(63, Black_4,      L"Black 4")
    ENUM_DEFAULT_VALUE(Default)
ENUM_END(FifamClubInterfaceColor07)

ENUM_BEGIN(FifamClubInterfaceColor08, UChar)
    ENUM_MEMBER( 0,  Default      , L"Default")
    ENUM_MEMBER( 1,  Black        , L"Black")
    ENUM_MEMBER( 2,  Grey         , L"Grey")
    ENUM_MEMBER( 3,  White        , L"White")
    ENUM_MEMBER( 4,  Crimson      , L"Crimson")
    ENUM_MEMBER( 5,  FireBrick    , L"FireBrick")
    ENUM_MEMBER( 6,  Tomato       , L"Tomato")
    ENUM_MEMBER( 7,  Maroon       , L"Maroon")
    ENUM_MEMBER( 8,  Saddle       , L"Saddle")
    ENUM_MEMBER( 9,  Peru         , L"Peru")
    ENUM_MEMBER(10,  Sienna       , L"Sienna")
    ENUM_MEMBER(11,  Chocolate    , L"Chocolate")
    ENUM_MEMBER(12,  Orange       , L"Orange")
    ENUM_MEMBER(13,  Sandy        , L"Sandy")
    ENUM_MEMBER(14,  Gold         , L"Gold")
    ENUM_MEMBER(15,  Banana       , L"Banana")
    ENUM_MEMBER(16,  Citrus       , L"Citrus")
    ENUM_MEMBER(17,  LemonChiffon , L"LemonChiffon")
    ENUM_MEMBER(18,  Chartreuse   , L"Chartreuse")
    ENUM_MEMBER(19,  Olive        , L"Olive")
    ENUM_MEMBER(20,  Lime         , L"Lime")
    ENUM_MEMBER(21,  Forest       , L"Forest")
    ENUM_MEMBER(22,  Lawn         , L"Lawn")
    ENUM_MEMBER(23,  Seaweed      , L"Seaweed")
    ENUM_MEMBER(24,  Pale         , L"Pale")
    ENUM_MEMBER(25,  MintCream    , L"MintCream")
    ENUM_MEMBER(26,  Aqua         , L"Aqua")
    ENUM_MEMBER(27,  Teal         , L"Teal")
    ENUM_MEMBER(28,  Alice        , L"Alice")
    ENUM_MEMBER(29,  Cornflower   , L"Cornflower")
    ENUM_MEMBER(30,  Steel        , L"Steel")
    ENUM_MEMBER(31,  Sky          , L"Sky")
    ENUM_MEMBER(32,  Ocean        , L"Ocean")
    ENUM_MEMBER(33,  Midnight     , L"Midnight")
    ENUM_MEMBER(34,  Royal        , L"Royal")
    ENUM_MEMBER(35,  Indigo       , L"Indigo")
    ENUM_MEMBER(36,  Slate        , L"Slate")
    ENUM_MEMBER(37,  Lavender     , L"Lavender")
    ENUM_MEMBER(38,  Thistle      , L"Thistle")
    ENUM_MEMBER(39,  Plum         , L"Plum")
    ENUM_MEMBER(40,  Pink         , L"Pink")
    ENUM_MEMBER(41,  Fuchsia      , L"Fuchsia")
    ENUM_MEMBER(42,  Orchid       , L"Orchid")
    ENUM_MEMBER(43,  Magenta      , L"Magenta")
    ENUM_DEFAULT_VALUE(Default)
ENUM_END(FifamClubInterfaceColor08)
