#pragma once
#include "FifamTypes.h"
#include "FifamEnum.h"

ENUM_BEGIN(FifamPlayerCharacter, UInt64)
    ENUM_MEMBER(0x1,           AttitudeToWin,        L"AttitudeToWin") 
    ENUM_MEMBER(0x2,           Complacent,           L"Complacent") 
    ENUM_MEMBER(0x4,           StrongNerves,         L"StrongNerves") 
    ENUM_MEMBER(0x8,           WeakNerves,           L"WeakNerves") 
    ENUM_MEMBER(0x10,          Fairness,             L"Fairness") 
    ENUM_MEMBER(0x20,          HardMan,              L"HardMan") 
    ENUM_MEMBER(0x40,          Introvert,            L"Introvert") 
    ENUM_MEMBER(0x80,          IdentificationHigh,   L"IdentificationHigh") 
    ENUM_MEMBER(0x100,         IdentificationLow,    L"IdentificationLow") 
    ENUM_MEMBER(0x200,         LanguageGenius,       L"LanguageGenius") 
    ENUM_MEMBER(0x400,         MediaDarling,         L"MediaDarling") 
    ENUM_MEMBER(0x800,         ScandalProne,         L"ScandalProne") 
    ENUM_MEMBER(0x1000,        Flexibility,          L"Flexibility") 
    ENUM_MEMBER(0x2000,        Inflexibility,        L"Inflexibility") 
    ENUM_MEMBER(0x4000,        Ambition,             L"Ambition") 
    ENUM_MEMBER(0x8000,        HighTrainingWorkRate, L"HighTrainingWorkRate") 
    ENUM_MEMBER(0x10000,       LazyInTraining,       L"LazyInTraining") 
    ENUM_MEMBER(0x20000,       Temperament,          L"Temperament") 
    ENUM_MEMBER(0x40000,       FansFavorite,         L"FansFavorite") 
    ENUM_MEMBER(0x80000,       Adaptability,         L"Adaptability") 
    ENUM_MEMBER(0x100000,      Professionalism,      L"Professionalism") 
    ENUM_MEMBER(0x200000,      LongThrows,           L"LongThrows") 
    ENUM_MEMBER(0x400000,      DrivenFreeKicks,      L"DrivenFreeKicks") 
    ENUM_MEMBER(0x800000,      InjuryProne,          L"InjuryProne") 
    ENUM_MEMBER(0x1000000,     Composure,            L"Composure") 
    ENUM_MEMBER(0x2000000,     Teamplayer,           L"Teamplayer") 
    ENUM_MEMBER(0x4000000,     Egoist,               L"Egoist") 
    ENUM_MEMBER(0x8000000,     LacksAmbition,        L"LacksAmbition") 
    ENUM_MEMBER(0x10000000,    LittleInjuryProne,    L"LittleInjuryProne") 
    ENUM_MEMBER(0x20000000,    LongThrowOuts,        L"LongThrowOuts") 
    ENUM_MEMBER(0x40000000,    UninterestedInMedia,  L"UninterestedInMedia") 
    ENUM_MEMBER(0x80000000,    Forgiving,            L"Forgiving") 
    ENUM_MEMBER(0x100000000,   NotForgiving,         L"NotForgiving") 
    ENUM_MEMBER(0x200000000,   HappyMan,             L"HappyMan") 
    ENUM_MEMBER(0x400000000,   Critic,               L"Critic") 
    ENUM_MEMBER(0x800000000,   Extrovert,            L"Extrovert") 
    ENUM_MEMBER(0x1000000000,  Independent,          L"Independent") 
    ENUM_MEMBER(0x2000000000,  NeedsAttention,       L"NeedsAttention") 
    ENUM_MEMBER(0x4000000000,  DoesntLikeNewLang,    L"DoesntLikeNewLang") 
    ENUM_MEMBER(0x8000000000,  Diva,                 L"Diva")
    ENUM_MEMBER(0x10000000000, LifestyleIcon,        L"LifestyleIcon")
ENUM_END(FifamPlayerCharacter)
