#pragma once
#include "FifamTypes.h"
#include "FifamEnum.h"

ENUM_BEGIN(FifamCupSystemType, UInt)
    ENUM_MEMBER( 0, None,       L"None")
    ENUM_MEMBER( 1, FA_Germany, L"FA_Germany")
    ENUM_MEMBER( 2, FA_England, L"FA_England")
    ENUM_MEMBER( 3, FA_France,  L"FA_France")
    ENUM_MEMBER( 4, FA_Spain,   L"FA_Spain")
    ENUM_MEMBER( 5, FA_Italy,   L"FA_Italy")
    ENUM_MEMBER( 6, LeagueCup_Germany, L"LeagueCup_Germany")
    ENUM_MEMBER( 7, LeagueCup_England, L"LeagueCup_England")
    ENUM_MEMBER( 8, LeagueCup_France, L"LeagueCup_France")
    ENUM_MEMBER( 9, CC_FA_Germany_32_1, L"CC_FA_Germany_32_1")
    ENUM_MEMBER(10, CC_FA_Germany_32_2, L"CC_FA_Germany_32_2")
    ENUM_MEMBER(11, FA_Scotland, L"FA_Scotland")
    ENUM_MEMBER(12, LeagueCup_Scotland, L"LeagueCup_Scotland")
    ENUM_MEMBER(13, LeaguecupDiv2And3, L"LeaguecupDiv2And3")
    ENUM_MEMBER(14, ConferenceCup, L"ConferenceCup")
    ENUM_MEMBER(15, Supercup1Leg, L"Supercup1Leg")
    ENUM_MEMBER(16, Supercup2Leg, L"Supercup2Leg")
    ENUM_MEMBER(17, FriendlyMatch, L"FriendlyMatch")
    ENUM_MEMBER(18, Tournament4Teams, L"Tournament4Teams")
    ENUM_MEMBER(19, RelegationSwitherland, L"RelegationSwitherland")
    ENUM_MEMBER(20, RelegationEngland3, L"RelegationEngland3")
    ENUM_MEMBER(21, FA_Cup_Small, L"FA_Cup_Small")
    ENUM_MEMBER(22, CC_FA_Germany_128,  L"CC_FA_Germany_128")
    ENUM_MEMBER(23, CC_FA_Germany_64, L"CC_FA_Germany_64")
    ENUM_MEMBER(24, CC_FA_Germany_32_3, L"CC_FA_Germany_32_3")
    ENUM_MEMBER(25, CC_FA_Germany_64_32, L"CC_FA_Germany_64_32")
    ENUM_DEFAULT_VALUE(None)
    ENUM_DEFAULT_READ_WRITE
ENUM_END(FifamCupSystemType)
