#pragma once
#include "FifamTypes.h"
#include "FifamEnum.h"

Bool GetNationCustomReplacement(UChar nationId, UChar &translatedNationId);

ENUM_BEGIN(FifamNation, UChar)
    ENUM_MEMBER(  0, None,                  L"None")
    ENUM_MEMBER(  1, Albania,               L"Albania")
    ENUM_MEMBER(  2, Andorra,               L"Andorra")
    ENUM_MEMBER(  3, Armenia,               L"Armenia")
    ENUM_MEMBER(  4, Austria,               L"Austria")
    ENUM_MEMBER(  5, Azerbaijan,            L"Azerbaijan")
    ENUM_MEMBER(  6, Belarus,               L"Belarus")
    ENUM_MEMBER(  7, Belgium,               L"Belgium")
    ENUM_MEMBER(  8, Bosnia_Herzegovina,    L"Bosnia-Herzegovina")
    ENUM_MEMBER(  9, Bulgaria,              L"Bulgaria")
    ENUM_MEMBER( 10, Croatia,               L"Croatia")
    ENUM_MEMBER( 11, Cyprus,                L"Cyprus")
    ENUM_MEMBER( 12, Czech_Republic,        L"Czech Republic")
    ENUM_MEMBER( 13, Denmark,               L"Denmark")
    ENUM_MEMBER( 14, England,               L"England")
    ENUM_MEMBER( 15, Estonia,               L"Estonia")
    ENUM_MEMBER( 16, Faroe_Islands,         L"Faroe Islands")
    ENUM_MEMBER( 17, Finland,               L"Finland")
    ENUM_MEMBER( 18, France,                L"France")
    ENUM_MEMBER( 19, FYR_Macedonia,         L"FYR Macedonia")
    ENUM_MEMBER( 20, Georgia,               L"Georgia")
    ENUM_MEMBER( 21, Germany,               L"Germany")
    ENUM_MEMBER( 22, Greece,                L"Greece")
    ENUM_MEMBER( 23, Hungary,               L"Hungary")
    ENUM_MEMBER( 24, Iceland,               L"Iceland")
    ENUM_MEMBER( 25, Ireland,               L"Ireland")
    ENUM_MEMBER( 26, Israel,                L"Israel")
    ENUM_MEMBER( 27, Italy,                 L"Italy")
    ENUM_MEMBER( 28, Latvia,                L"Latvia")
    ENUM_MEMBER( 29, Liechtenstein,         L"Liechtenstein")
    ENUM_MEMBER( 30, Lithuania,             L"Lithuania")
    ENUM_MEMBER( 31, Luxembourg,            L"Luxembourg")
    ENUM_MEMBER( 32, Malta,                 L"Malta")
    ENUM_MEMBER( 33, Moldova,               L"Moldova")
    ENUM_MEMBER( 34, Netherlands,           L"Netherlands")
    ENUM_MEMBER( 35, Northern_Ireland,      L"Northern Ireland")
    ENUM_MEMBER( 36, Norway,                L"Norway")
    ENUM_MEMBER( 37, Poland,                L"Poland")
    ENUM_MEMBER( 38, Portugal,              L"Portugal")
    ENUM_MEMBER( 39, Romania,               L"Romania")
    ENUM_MEMBER( 40, Russia,                L"Russia")
    ENUM_MEMBER( 41, San_Marino,            L"San Marino")
    ENUM_MEMBER( 42, Scotland,              L"Scotland")
    ENUM_MEMBER( 43, Slovakia,              L"Slovakia")
    ENUM_MEMBER( 44, Slovenia,              L"Slovenia")
    ENUM_MEMBER( 45, Spain,                 L"Spain")
    ENUM_MEMBER( 46, Sweden,                L"Sweden")
    ENUM_MEMBER( 47, Switzerland,           L"Switzerland")
    ENUM_MEMBER( 48, Turkey,                L"Turkey")
    ENUM_MEMBER( 49, Ukraine,               L"Ukraine")
    ENUM_MEMBER( 50, Wales,                 L"Wales")
    ENUM_MEMBER( 51, Serbia,                L"Serbia")
    ENUM_MEMBER( 52, Argentina,             L"Argentina")
    ENUM_MEMBER( 53, Bolivia,               L"Bolivia")
    ENUM_MEMBER( 54, Brazil,                L"Brazil")
    ENUM_MEMBER( 55, Chile,                 L"Chile")
    ENUM_MEMBER( 56, Colombia,              L"Colombia")
    ENUM_MEMBER( 57, Ecuador,               L"Ecuador")
    ENUM_MEMBER( 58, Paraguay,              L"Paraguay")
    ENUM_MEMBER( 59, Peru,                  L"Peru")
    ENUM_MEMBER( 60, Uruguay,               L"Uruguay")
    ENUM_MEMBER( 61, Venezuela,             L"Venezuela")
    ENUM_MEMBER( 62, Anguilla,              L"Anguilla")
    ENUM_MEMBER( 63, Antigua_and_Barbuda,   L"Antigua and Barbuda")
    ENUM_MEMBER( 64, Aruba,                 L"Aruba")
    ENUM_MEMBER( 65, Bahamas,               L"Bahamas")
    ENUM_MEMBER( 66, Barbados,              L"Barbados")
    ENUM_MEMBER( 67, Belize,                L"Belize")
    ENUM_MEMBER( 68, Bermuda,               L"Bermuda")
    ENUM_MEMBER( 69, British_Virgin_Is,     L"British Virgin Is.")
    ENUM_MEMBER( 70, Canada,                L"Canada")
    ENUM_MEMBER( 71, Cayman_Islands,        L"Cayman Islands")
    ENUM_MEMBER( 72, Costa_Rica,            L"Costa Rica")
    ENUM_MEMBER( 73, Cuba,                  L"Cuba")
    ENUM_MEMBER( 74, Dominica,              L"Dominica")
    ENUM_MEMBER( 75, Dominican_Republic,    L"Dominican Republic")
    ENUM_MEMBER( 76, El_Salvador,           L"El Salvador")
    ENUM_MEMBER( 77, Grenada,               L"Grenada")
    ENUM_MEMBER( 78, Guatemala,             L"Guatemala")
    ENUM_MEMBER( 79, Guyana,                L"Guyana")
    ENUM_MEMBER( 80, Haiti,                 L"Haiti")
    ENUM_MEMBER( 81, Honduras,              L"Honduras")
    ENUM_MEMBER( 82, Jamaica,               L"Jamaica")
    ENUM_MEMBER( 83, Mexico,                L"Mexico")
    ENUM_MEMBER( 84, Montserrat,            L"Montserrat")
    ENUM_MEMBER( 85, Netherlands_Antil,     L"Netherlands Antil.")
    ENUM_MEMBER( 86, Nicaragua,             L"Nicaragua")
    ENUM_MEMBER( 87, Panama,                L"Panama")
    ENUM_MEMBER( 88, Puerto_Rico,           L"Puerto Rico")
    ENUM_MEMBER( 89, St_Kitts_Nevis,        L"St. Kitts & Nevis")
    ENUM_MEMBER( 90, St_Lucia,              L"St. Lucia")
    ENUM_MEMBER( 91, St_Vincent_Gren,       L"St. Vincent & Gren.")
    ENUM_MEMBER( 92, Surinam,               L"Surinam")
    ENUM_MEMBER( 93, Trinidad_Tobago,       L"Trinidad & Tobago")
    ENUM_MEMBER( 94, Turks_and_Caicos,      L"Turks and Caicos")
    ENUM_MEMBER( 95, United_States,         L"United States")
    ENUM_MEMBER( 96, US_Virgin_Islands,     L"US Virgin Islands")
    ENUM_MEMBER( 97, Algeria,               L"Algeria")
    ENUM_MEMBER( 98, Angola,                L"Angola")
    ENUM_MEMBER( 99, Benin,                 L"Benin")
    ENUM_MEMBER(100, Botswana,              L"Botswana")
    ENUM_MEMBER(101, Burkina_Faso,          L"Burkina Faso")
    ENUM_MEMBER(102, Burundi,               L"Burundi")
    ENUM_MEMBER(103, Cameroon,              L"Cameroon")
    ENUM_MEMBER(104, Cape_Verde_Islands,    L"Cape Verde Islands")
    ENUM_MEMBER(105, Central_African_Rep,   L"Central African Rep.")
    ENUM_MEMBER(106, Chad,                  L"Chad")
    ENUM_MEMBER(107, Congo,                 L"Congo")
    ENUM_MEMBER(108, Cote_d_Ivoire,         L"Cote d' Ivoire")
    ENUM_MEMBER(109, Djibouti,              L"Djibouti")
    ENUM_MEMBER(110, DR_Congo,              L"DR Congo")
    ENUM_MEMBER(111, Egypt,                 L"Egypt")
    ENUM_MEMBER(112, Equatorial_Guinea,     L"Equatorial Guinea")
    ENUM_MEMBER(113, Eritrea,               L"Eritrea")
    ENUM_MEMBER(114, Ethiopia,              L"Ethiopia")
    ENUM_MEMBER(115, Gabon,                 L"Gabon")
    ENUM_MEMBER(116, Gambia,                L"Gambia")
    ENUM_MEMBER(117, Ghana,                 L"Ghana")
    ENUM_MEMBER(118, Guinea,                L"Guinea")
    ENUM_MEMBER(119, Guinea_Bissau,         L"Guinea-Bissau")
    ENUM_MEMBER(120, Kenya,                 L"Kenya")
    ENUM_MEMBER(121, Lesotho,               L"Lesotho")
    ENUM_MEMBER(122, Liberia,               L"Liberia")
    ENUM_MEMBER(123, Libya,                 L"Libya")
    ENUM_MEMBER(124, Madagascar,            L"Madagascar")
    ENUM_MEMBER(125, Malawi,                L"Malawi")
    ENUM_MEMBER(126, Mali,                  L"Mali")
    ENUM_MEMBER(127, Mauritania,            L"Mauritania")
    ENUM_MEMBER(128, Mauritius,             L"Mauritius")
    ENUM_MEMBER(129, Morocco,               L"Morocco")
    ENUM_MEMBER(130, Mozambique,            L"Mozambique")
    ENUM_MEMBER(131, Namibia,               L"Namibia")
    ENUM_MEMBER(132, Niger,                 L"Niger")
    ENUM_MEMBER(133, Nigeria,               L"Nigeria")
    ENUM_MEMBER(134, Rwanda,                L"Rwanda")
    ENUM_MEMBER(135, Sao_Tome_e_Principe,   L"Sao Tome e Principe")
    ENUM_MEMBER(136, Senegal,               L"Senegal")
    ENUM_MEMBER(137, Seychelles,            L"Seychelles")
    ENUM_MEMBER(138, Sierra_Leone,          L"Sierra Leone")
    ENUM_MEMBER(139, Somalia,               L"Somalia")
    ENUM_MEMBER(140, South_Africa,          L"South Africa")
    ENUM_MEMBER(141, Sudan,                 L"Sudan")
    ENUM_MEMBER(142, Swaziland,             L"Swaziland")
    ENUM_MEMBER(143, Tanzania,              L"Tanzania")
    ENUM_MEMBER(144, Togo,                  L"Togo")
    ENUM_MEMBER(145, Tunisia,               L"Tunisia")
    ENUM_MEMBER(146, Uganda,                L"Uganda")
    ENUM_MEMBER(147, Zambia,                L"Zambia")
    ENUM_MEMBER(148, Zimbabwe,              L"Zimbabwe")
    ENUM_MEMBER(149, Afghanistan,           L"Afghanistan")
    ENUM_MEMBER(150, Bahrain,               L"Bahrain")
    ENUM_MEMBER(151, Bangladesh,            L"Bangladesh")
    ENUM_MEMBER(152, Bhutan,                L"Bhutan")
    ENUM_MEMBER(153, Brunei_Darussalam,     L"Brunei Darussalam")
    ENUM_MEMBER(154, Cambodia,              L"Cambodia")
    ENUM_MEMBER(155, China_PR,              L"China PR")
    ENUM_MEMBER(156, Taiwan,                L"Taiwan")
    ENUM_MEMBER(157, Guam,                  L"Guam")
    ENUM_MEMBER(158, Hong_Kong,             L"Hong Kong")
    ENUM_MEMBER(159, India,                 L"India")
    ENUM_MEMBER(160, Indonesia,             L"Indonesia")
    ENUM_MEMBER(161, Iran,                  L"Iran")
    ENUM_MEMBER(162, Iraq,                  L"Iraq")
    ENUM_MEMBER(163, Japan,                 L"Japan")
    ENUM_MEMBER(164, Jordan,                L"Jordan")
    ENUM_MEMBER(165, Kazakhstan,            L"Kazakhstan")
    ENUM_MEMBER(166, Korea_DPR,             L"Korea DPR")
    ENUM_MEMBER(167, Korea_Republic,        L"Korea Republic")
    ENUM_MEMBER(168, Kuwait,                L"Kuwait")
    ENUM_MEMBER(169, Kyrgyzstan,            L"Kyrgyzstan")
    ENUM_MEMBER(170, Laos,                  L"Laos")
    ENUM_MEMBER(171, Lebanon,               L"Lebanon")
    ENUM_MEMBER(172, Macao,                 L"Macao")
    ENUM_MEMBER(173, Malaysia,              L"Malaysia")
    ENUM_MEMBER(174, Maldives,              L"Maldives")
    ENUM_MEMBER(175, Mongolia,              L"Mongolia")
    ENUM_MEMBER(176, Myanmar,               L"Myanmar")
    ENUM_MEMBER(177, Nepal,                 L"Nepal")
    ENUM_MEMBER(178, Oman,                  L"Oman")
    ENUM_MEMBER(179, Pakistan,              L"Pakistan")
    ENUM_MEMBER(180, Palestinian_Authority, L"Palestinian Authority")
    ENUM_MEMBER(181, Philippines,           L"Philippines")
    ENUM_MEMBER(182, Qatar,                 L"Qatar")
    ENUM_MEMBER(183, Saudi_Arabia,          L"Saudi Arabia")
    ENUM_MEMBER(184, Singapore,             L"Singapore")
    ENUM_MEMBER(185, Sri_Lanka,             L"Sri Lanka")
    ENUM_MEMBER(186, Syria,                 L"Syria")
    ENUM_MEMBER(187, Tajikistan,            L"Tajikistan")
    ENUM_MEMBER(188, Thailand,              L"Thailand")
    ENUM_MEMBER(189, Turkmenistan,          L"Turkmenistan")
    ENUM_MEMBER(190, United_Arab_Emirates,  L"United Arab Emirates")
    ENUM_MEMBER(191, Uzbekistan,            L"Uzbekistan")
    ENUM_MEMBER(192, Vietnam,               L"Vietnam")
    ENUM_MEMBER(193, Yemen,                 L"Yemen")
    ENUM_MEMBER(194, American_Samoa,        L"American Samoa")
    ENUM_MEMBER(195, Australia,             L"Australia")
    ENUM_MEMBER(196, Cook_Islands,          L"Cook Islands")
    ENUM_MEMBER(197, Fiji,                  L"Fiji")
    ENUM_MEMBER(198, New_Zealand,           L"New Zealand")
    ENUM_MEMBER(199, Papua_New_Guinea,      L"Papua New Guinea")
    ENUM_MEMBER(200, Samoa,                 L"Samoa")
    ENUM_MEMBER(201, Solomon_Islands,       L"Solomon Islands")
    ENUM_MEMBER(202, Tahiti,                L"Tahiti")
    ENUM_MEMBER(203, Tonga,                 L"Tonga")
    ENUM_MEMBER(204, Vanuatu,               L"Vanuatu")
    ENUM_MEMBER(205, Gibraltar,             L"Gibraltar")
    ENUM_MEMBER(206, Montenegro,            L"Montenegro")
    ENUM_MEMBER(207, Greenland,             L"Greenland")
    ENUM_DEFAULT_VALUE(None)

    ENUM_READ(reader, str) {
        if (!str.empty()) {
            UChar id = Utils::SafeConvertInt<UChar>(str);
            if (reader.GetGameId() <= 7) {
                if (id == 206)
                    id = Greenland;
                else if (id == 207) {
                    SetUnknown(id);
                    SetDefaultValue();
                    return;
                }
            }
            SetFromInt(id);
        }
        else
            SetDefaultValue();
    }

    ENUM_WRITE(writer) {
        UChar id = ToInt();
        if (!GetNationCustomReplacement(id, id)) {
            if (writer.GetGameId() <= 7) {
                if (ToInt() == Montenegro)
                    writer.WriteOne(Serbia);
            }
        }
        if (writer.GetGameId() <= 7 && id == Greenland)
            id = 206;
        writer.WriteOne(id);
    }
ENUM_END(FifamNation)
