#pragma once
#include "FifamTypes.h"
#include "FifamEnum.h"

ENUM_BEGIN(FifamStaffSkillID, UChar)
    ENUM_MEMBER(0, Tactics, L"Tactics")
    ENUM_MEMBER(1, FieldPlayerTraining, L"FieldPlayerTraining")
    ENUM_MEMBER(2, GoalkeeperTraining, L"GoalkeeperTraining")
    ENUM_MEMBER(3, FitnessTraining, L"FitnessTraining")
    ENUM_MEMBER(4, SkillEstimation, L"SkillEstimation")
    ENUM_MEMBER(5, TeamEstimation, L"TeamEstimation")
    ENUM_MEMBER(6, MotivationAbility, L"MotivationAbility")
    ENUM_MEMBER(7, BoneInjury, L"BoneInjury")
    ENUM_MEMBER(8, KneeInjury, L"KneeInjury")
    ENUM_MEMBER(9, MuscleInjury, L"MuscleInjury")
    ENUM_MEMBER(10, InjuryPrevention, L"InjuryPrevention")
    ENUM_MEMBER(11, RegenerationAbility, L"RegenerationAbility")
    ENUM_MEMBER(12, Arbitrate, L"Arbitrate")
    ENUM_MEMBER(13, Negotiation, L"Negotiation")
    ENUM_MEMBER(14, Marketing, L"Marketing")
    ENUM_MEMBER(15, Sponsoring, L"Sponsoring")
    ENUM_MEMBER(16, Construction, L"Construction")
    ENUM_MEMBER(17, PR, L"PR")
    ENUM_MEMBER(18, FanContact, L"FanContact")
    ENUM_MEMBER(19, SportsLaw, L"SportsLaw")
    ENUM_MEMBER(20, LaborLaw, L"LaborLaw")
    ENUM_MEMBER(21, GeneralScouting, L"GeneralScouting")
    ENUM_MEMBER(22, TalentEstimation, L"TalentEstimation")
    ENUM_MEMBER(23, FieldSkillsEstimation, L"FieldSkillsEstimation")
    ENUM_MEMBER(24, GoalkeeperSkillsEstimation, L"GoalkeeperSkillsEstimation")
    ENUM_MEMBER(25, MentalSkillsEstimation, L"MentalSkillsEstimation")
    ENUM_MEMBER(26, PhysicalSkillsEstimation, L"PhysicalSkillsEstimation")
    ENUM_MEMBER(27, Networking, L"Networking")
    ENUM_DEFAULT_VALUE(Tactics)
    ENUM_DEFAULT_READ_WRITE
ENUM_END(FifamStaffSkillID)
