#include "FifaStoryModePlayer.h"
#include "FifaDatabase.h"
#include <sstream>

unsigned int FifaStoryModePlayer::GetId() {
    return internal.playerid;
}

void FifaStoryModePlayer::Internal::Read(FifaDataFile::Line &line) {
    switch (FifaDatabase::m_currentGameVersion) {
    case 17:
        line >> shoetypecode >> haircolorcode >> facialhairtypecode >> curve >> jerseystylecode >> agility >> accessorycode4 >> gksavetype >> positioning >> hairtypecode >> standingtackle >> preferredposition3 >> longpassing >> penalties >> animfreekickstartposcode >> animpenaltieskickstylecode >> isretiring >> longshots >> gkdiving >> interceptions >> shoecolorcode2 >> crossing >> potential >> gkreflexes >> finishingcode1 >> reactions >> composure >> vision >> contractvaliduntil >> animpenaltiesapproachcode >> finishing >> dribbling >> slidingtackle >> accessorycode3 >> accessorycolourcode1 >> headtypecode >> firstnameid >> sprintspeed >> height >> hasseasonaljersey >> preferredposition2 >> strength >> birthdate >> preferredposition1 >> ballcontrol >> shotpower >> trait1 >> socklengthcode >> weight >> hashighqualityhead >> gkglovetypecode >> balance >> gender >> gkkicking >> lastnameid >> internationalrep >> animpenaltiesmotionstylecode >> shortpassing >> freekickaccuracy >> skillmoves >> artificialkey >> usercaneditname >> attackingworkrate >> finishingcode2 >> aggression >> acceleration >> headingaccuracy >> eyebrowcode >> runningcode2 >> modifier >> gkhandling >> eyecolorcode >> jerseysleevelengthcode >> accessorycolourcode3 >> accessorycode1 >> playerjointeamdate >> headclasscode >> defensiveworkrate >> nationality >> preferredfoot >> sideburnscode >> weakfootabilitytypecode >> jumping >> skintypecode >> gkkickstyle >> stamina >> playerid >> marking >> accessorycolourcode4 >> gkpositioning >> trait2 >> skintonecode >> shortstyle >> overallrating >> emotion >> jerseyfit >> accessorycode2 >> shoedesigncode >> playerjerseynameid >> shoecolorcode1 >> commonnameid >> bodytypecode >> animpenaltiesstartposcode >> runningcode1 >> preferredposition4 >> volleys >> accessorycolourcode2 >> facialhaircolorcode;
        break;
    case 18:
        line >> firstnameid >> lastnameid >> playerjerseynameid >> commonnameid >> trait2 >> haircolorcode >> facialhairtypecode >> curve >> jerseystylecode >> agility >> accessorycode4 >> gksavetype >> positioning >> tattooleftarm >> hairtypecode >> standingtackle >> tattoobackneck >> preferredposition3 >> longpassing >> penalties >> animfreekickstartposcode >> animpenaltieskickstylecode >> isretiring >> longshots >> gkdiving >> interceptions >> shoecolorcode2 >> crossing >> potential >> gkreflexes >> finishingcode1 >> reactions >> composure >> vision >> contractvaliduntil >> animpenaltiesapproachcode >> finishing >> dribbling >> slidingtackle >> accessorycode3 >> accessorycolourcode1 >> headtypecode >> sprintspeed >> height >> hasseasonaljersey >> preferredposition2 >> strength >> shoetypecode >> birthdate >> preferredposition1 >> ballcontrol >> shotpower >> trait1 >> socklengthcode >> weight >> hashighqualityhead >> gkglovetypecode >> tattoorightarm >> balance >> gender >> gkkicking >> internationalrep >> animpenaltiesmotionstylecode >> shortpassing >> freekickaccuracy >> skillmoves >> artificialkey >> usercaneditname >> attackingworkrate >> finishingcode2 >> aggression >> acceleration >> headingaccuracy >> iscustomized >> eyebrowcode >> runningcode2 >> modifier >> gkhandling >> eyecolorcode >> jerseysleevelengthcode >> accessorycolourcode3 >> accessorycode1 >> playerjointeamdate >> headclasscode >> defensiveworkrate >> nationality >> preferredfoot >> sideburnscode >> weakfootabilitytypecode >> jumping >> skintypecode >> tattoorightneck >> gkkickstyle >> stamina >> playerid >> marking >> accessorycolourcode4 >> gkpositioning >> headvariation >> skintonecode >> shortstyle >> overallrating >> tattooleftneck >> emotion >> jerseyfit >> accessorycode2 >> shoedesigncode >> shoecolorcode1 >> hairstylecode >> bodytypecode >> animpenaltiesstartposcode >> runningcode1 >> preferredposition4 >> volleys >> accessorycolourcode2 >> facialhaircolorcode;
        break;
    case 19:
        line >> firstnameid >> lastnameid >> playerjerseynameid >> commonnameid >> trait2 >> haircolorcode >> facialhairtypecode >> curve >> jerseystylecode >> agility >> accessorycode4 >> gksavetype >> positioning >> tattooleftarm >> hairtypecode >> standingtackle >> tattoobackneck >> preferredposition3 >> longpassing >> penalties >> animfreekickstartposcode >> animpenaltieskickstylecode >> isretiring >> longshots >> gkdiving >> interceptions >> shoecolorcode2 >> crossing >> potential >> gkreflexes >> finishingcode1 >> reactions >> composure >> vision >> contractvaliduntil >> animpenaltiesapproachcode >> finishing >> dribbling >> slidingtackle >> accessorycode3 >> accessorycolourcode1 >> headtypecode >> sprintspeed >> height >> hasseasonaljersey >> preferredposition2 >> strength >> shoetypecode >> birthdate >> preferredposition1 >> ballcontrol >> shotpower >> trait1 >> socklengthcode >> weight >> hashighqualityhead >> gkglovetypecode >> tattoorightarm >> balance >> gender >> headassetid >> gkkicking >> internationalrep >> animpenaltiesmotionstylecode >> shortpassing >> freekickaccuracy >> skillmoves >> faceposerpreset >> artificialkey >> usercaneditname >> attackingworkrate >> finishingcode2 >> aggression >> acceleration >> headingaccuracy >> iscustomized >> eyebrowcode >> runningcode2 >> modifier >> gkhandling >> eyecolorcode >> jerseysleevelengthcode >> accessorycolourcode3 >> accessorycode1 >> playerjointeamdate >> headclasscode >> defensiveworkrate >> nationality >> preferredfoot >> sideburnscode >> weakfootabilitytypecode >> jumping >> skintypecode >> tattoorightneck >> gkkickstyle >> stamina >> playerid >> marking >> accessorycolourcode4 >> gkpositioning >> headvariation >> skillmoveslikelihood >> skintonecode >> shortstyle >> overallrating >> tattooleftneck >> emotion >> jerseyfit >> accessorycode2 >> shoedesigncode >> shoecolorcode1 >> hairstylecode >> bodytypecode >> animpenaltiesstartposcode >> runningcode1 >> preferredposition4 >> volleys >> accessorycolourcode2 >> facialhaircolorcode;
        break;
    case 20:
        line >> firstnameid >> lastnameid >> playerjerseynameid >> commonnameid >> skintypecode >> trait2 >> bodytypecode >> haircolorcode >> facialhairtypecode >> curve >> jerseystylecode >> agility >> tattooback >> accessorycode4 >> gksavetype >> positioning >> tattooleftarm >> hairtypecode >> standingtackle >> preferredposition3 >> longpassing >> penalties >> animfreekickstartposcode >> animpenaltieskickstylecode >> isretiring >> longshots >> gkdiving >> interceptions >> shoecolorcode2 >> crossing >> potential >> gkreflexes >> finishingcode1 >> reactions >> composure >> vision >> contractvaliduntil >> animpenaltiesapproachcode >> finishing >> dribbling >> slidingtackle >> accessorycode3 >> accessorycolourcode1 >> headtypecode >> sprintspeed >> height >> hasseasonaljersey >> tattoohead >> preferredposition2 >> strength >> shoetypecode >> birthdate >> preferredposition1 >> tattooleftleg >> ballcontrol >> shotpower >> trait1 >> socklengthcode >> weight >> hashighqualityhead >> gkglovetypecode >> tattoorightarm >> balance >> gender >> headassetid >> gkkicking >> internationalrep >> animpenaltiesmotionstylecode >> shortpassing >> freekickaccuracy >> skillmoves >> faceposerpreset >> artificialkey >> usercaneditname >> avatarpomid >> attackingworkrate >> finishingcode2 >> aggression >> acceleration >> headingaccuracy >> iscustomized >> eyebrowcode >> runningcode2 >> modifier >> gkhandling >> eyecolorcode >> jerseysleevelengthcode >> accessorycolourcode3 >> accessorycode1 >> playerjointeamdate >> headclasscode >> defensiveworkrate >> tattoofront >> nationality >> preferredfoot >> sideburnscode >> weakfootabilitytypecode >> jumping >> personality >> gkkickstyle >> stamina >> playerid >> marking >> accessorycolourcode4 >> gkpositioning >> headvariation >> skillmoveslikelihood >> skintonecode >> shortstyle >> overallrating >> smallsidedshoetypecode >> emotion >> runstylecode >> jerseyfit >> accessorycode2 >> shoedesigncode >> shoecolorcode1 >> hairstylecode >> animpenaltiesstartposcode >> runningcode1 >> preferredposition4 >> volleys >> accessorycolourcode2 >> tattoorightleg >> facialhaircolorcode;
        break;
    case 21:
        line >> firstnameid >> lastnameid >> playerjerseynameid >> commonnameid >> skintypecode >> trait2 >> haircolorcode >> facialhairtypecode >> curve >> jerseystylecode >> agility >> tattooback >> accessorycode4 >> gksavetype >> positioning >> tattooleftarm >> hairtypecode >> standingtackle >> preferredposition3 >> longpassing >> penalties >> animfreekickstartposcode >> animpenaltieskickstylecode >> isretiring >> longshots >> gkdiving >> interceptions >> shoecolorcode2 >> crossing >> potential >> gkreflexes >> finishingcode1 >> reactions >> composure >> vision >> contractvaliduntil >> animpenaltiesapproachcode >> finishing >> dribbling >> slidingtackle >> accessorycode3 >> accessorycolourcode1 >> headtypecode >> sprintspeed >> height >> hasseasonaljersey >> tattoohead >> preferredposition2 >> strength >> shoetypecode >> birthdate >> preferredposition1 >> tattooleftleg >> ballcontrol >> shotpower >> trait1 >> socklengthcode >> weight >> hashighqualityhead >> gkglovetypecode >> tattoorightarm >> balance >> gender >> headassetid >> gkkicking >> internationalrep >> animpenaltiesmotionstylecode >> shortpassing >> freekickaccuracy >> skillmoves >> faceposerpreset >> artificialkey >> usercaneditname >> avatarpomid >> attackingworkrate >> finishingcode2 >> aggression >> acceleration >> headingaccuracy >> iscustomized >> eyebrowcode >> runningcode2 >> modifier >> gkhandling >> eyecolorcode >> jerseysleevelengthcode >> accessorycolourcode3 >> accessorycode1 >> playerjointeamdate >> headclasscode >> defensiveworkrate >> tattoofront >> nationality >> preferredfoot >> sideburnscode >> weakfootabilitytypecode >> jumping >> personality >> gkkickstyle >> stamina >> playerid >> marking >> accessorycolourcode4 >> gkpositioning >> headvariation >> skillmoveslikelihood >> skintonecode >> shortstyle >> overallrating >> smallsidedshoetypecode >> emotion >> runstylecode >> jerseyfit >> accessorycode2 >> shoedesigncode >> shoecolorcode1 >> hairstylecode >> bodytypecode >> animpenaltiesstartposcode >> runningcode1 >> preferredposition4 >> volleys >> accessorycolourcode2 >> tattoorightleg >> facialhaircolorcode;
        break;
    case 22:
        line >> firstnameid >> lastnameid >> playerjerseynameid >> commonnameid >> skintypecode >> trait2 >> haircolorcode >> facialhairtypecode >> curve >> jerseystylecode >> agility >> tattooback >> accessorycode4 >> gksavetype >> positioning >> tattooleftarm >> hairtypecode >> standingtackle >> preferredposition3 >> longpassing >> penalties >> animfreekickstartposcode >> isretiring >> longshots >> gkdiving >> interceptions >> shoecolorcode2 >> crossing >> potential >> gkreflexes >> finishingcode1 >> reactions >> composure >> vision >> contractvaliduntil >> finishing >> dribbling >> slidingtackle >> accessorycode3 >> accessorycolourcode1 >> headtypecode >> driref >> sprintspeed >> height >> hasseasonaljersey >> tattoohead >> preferredposition2 >> strength >> shoetypecode >> birthdate >> preferredposition1 >> tattooleftleg >> ballcontrol >> phypos >> shotpower >> trait1 >> socklengthcode >> weight >> hashighqualityhead >> gkglovetypecode >> tattoorightarm >> balance >> gender >> headassetid >> gkkicking >> defspe >> internationalrep >> shortpassing >> freekickaccuracy >> skillmoves >> faceposerpreset >> artificialkey >> usercaneditname >> avatarpomid >> attackingworkrate >> finishingcode2 >> aggression >> acceleration >> paskic >> headingaccuracy >> iscustomized >> eyebrowcode >> runningcode2 >> modifier >> gkhandling >> eyecolorcode >> jerseysleevelengthcode >> accessorycolourcode3 >> accessorycode1 >> playerjointeamdate >> headclasscode >> defensiveworkrate >> tattoofront >> nationality >> preferredfoot >> sideburnscode >> weakfootabilitytypecode >> jumping >> personality >> gkkickstyle >> stamina >> playerid >> marking >> accessorycolourcode4 >> gkpositioning >> headvariation >> skillmoveslikelihood >> shohan >> skintonecode >> shortstyle >> overallrating >> smallsidedshoetypecode >> emotion >> runstylecode >> jerseyfit >> accessorycode2 >> shoedesigncode >> shoecolorcode1 >> hairstylecode >> bodytypecode >> animpenaltiesstartposcode >> pacdiv >> runningcode1 >> preferredposition4 >> volleys >> accessorycolourcode2 >> tattoorightleg >> facialhaircolorcode;
        break;
    case 23:
        line >> firstnameid >> lastnameid >> playerjerseynameid >> commonnameid >> skintypecode >> trait2 >> haircolorcode >> facialhairtypecode >> curve >> jerseystylecode >> agility >> tattooback >> accessorycode4 >> gksavetype >> positioning >> tattooleftarm >> hairtypecode >> standingtackle >> preferredposition3 >> longpassing >> penalties >> animfreekickstartposcode >> isretiring >> longshots >> gkdiving >> interceptions >> shoecolorcode2 >> crossing >> potential >> gkreflexes >> finishingcode1 >> reactions >> composure >> vision >> contractvaliduntil >> finishing >> dribbling >> slidingtackle >> accessorycode3 >> accessorycolourcode1 >> headtypecode >> driref >> sprintspeed >> height >> hasseasonaljersey >> tattoohead >> preferredposition2 >> strength >> shoetypecode >> birthdate >> preferredposition1 >> tattooleftleg >> ballcontrol >> phypos >> shotpower >> trait1 >> socklengthcode >> weight >> hashighqualityhead >> gkglovetypecode >> tattoorightarm >> balance >> gender >> headassetid >> gkkicking >> defspe >> internationalrep >> shortpassing >> freekickaccuracy >> skillmoves >> faceposerpreset >> artificialkey >> usercaneditname >> avatarpomid >> attackingworkrate >> finishingcode2 >> aggression >> acceleration >> paskic >> headingaccuracy >> iscustomized >> eyebrowcode >> runningcode2 >> modifier >> gkhandling >> eyecolorcode >> jerseysleevelengthcode >> accessorycolourcode3 >> accessorycode1 >> playerjointeamdate >> headclasscode >> defensiveworkrate >> tattoofront >> nationality >> preferredfoot >> sideburnscode >> weakfootabilitytypecode >> jumping >> personality >> gkkickstyle >> stamina >> playerid >> accessorycolourcode4 >> gkpositioning >> headvariation >> skillmoveslikelihood >> shohan >> skintonecode >> shortstyle >> overallrating >> smallsidedshoetypecode >> emotion >> runstylecode >> jerseyfit >> accessorycode2 >> shoedesigncode >> shoecolorcode1 >> hairstylecode >> bodytypecode >> animpenaltiesstartposcode >> pacdiv >> defensiveawareness >> runningcode1 >> preferredposition4 >> volleys >> accessorycolourcode2 >> tattoorightleg >> facialhaircolorcode;
        break;
    case 24:
        line >> firstnameid >> lastnameid >> playerjerseynameid >> commonnameid >> gkglovetypecode >> skintypecode >> haircolorcode >> facialhairtypecode >> curve >> jerseystylecode >> agility >> tattooback >> accessorycode4 >> gksavetype >> positioning >> tattooleftarm >> hairtypecode >> standingtackle >> preferredposition3 >> longpassing >> penalties >> animfreekickstartposcode >> isretiring >> longshots >> gkdiving >> icontrait2 >> interceptions >> shoecolorcode2 >> crossing >> potential >> gkreflexes >> finishingcode1 >> reactions >> composure >> vision >> contractvaliduntil >> finishing >> dribbling >> slidingtackle >> accessorycode3 >> accessorycolourcode1 >> headtypecode >> driref >> sprintspeed >> height >> hasseasonaljersey >> tattoohead >> preferredposition2 >> strength >> shoetypecode >> birthdate >> preferredposition1 >> tattooleftleg >> ballcontrol >> phypos >> shotpower >> trait1 >> socklengthcode >> weight >> hashighqualityhead >> tattoorightarm >> icontrait1 >> balance >> gender >> headassetid >> gkkicking >> defspe >> internationalrep >> shortpassing >> freekickaccuracy >> skillmoves >> faceposerpreset >> artificialkey >> usercaneditname >> avatarpomid >> attackingworkrate >> finishingcode2 >> aggression >> acceleration >> paskic >> headingaccuracy >> iscustomized >> eyebrowcode >> runningcode2 >> modifier >> gkhandling >> eyecolorcode >> jerseysleevelengthcode >> accessorycolourcode3 >> accessorycode1 >> playerjointeamdate >> headclasscode >> defensiveworkrate >> tattoofront >> nationality >> preferredfoot >> sideburnscode >> weakfootabilitytypecode >> jumping >> personality >> gkkickstyle >> stamina >> playerid >> accessorycolourcode4 >> gkpositioning >> headvariation >> skillmoveslikelihood >> trait2 >> shohan >> skintonecode >> shortstyle >> overallrating >> smallsidedshoetypecode >> emotion >> runstylecode >> muscularitycode >> jerseyfit >> accessorycode2 >> shoedesigncode >> shoecolorcode1 >> hairstylecode >> bodytypecode >> animpenaltiesstartposcode >> pacdiv >> defensiveawareness >> runningcode1 >> preferredposition4 >> volleys >> accessorycolourcode2 >> tattoorightleg >> facialhaircolorcode;
        break;
    case 25:
        line >> firstnameid >> lastnameid >> playerjerseynameid >> commonnameid >> role3 >> gkglovetypecode >> role2 >> role1 >> eyebrowcode >> skintypecode >> haircolorcode >> facialhairtypecode >> curve >> jerseystylecode >> agility >> tattooback >> accessorycode4 >> gksavetype >> positioning >> tattooleftarm >> hairtypecode >> standingtackle >> preferredposition3 >> longpassing >> penalties >> animfreekickstartposcode >> lipcolor >> isretiring >> longshots >> gkdiving >> icontrait2 >> interceptions >> shoecolorcode2 >> crossing >> potential >> gkreflexes >> finishingcode1 >> reactions >> composure >> skinsurfacepack >> vision >> contractvaliduntil >> finishing >> dribbling >> slidingtackle >> accessorycode3 >> accessorycolourcode1 >> headtypecode >> driref >> sprintspeed >> undershortstyle >> height >> hasseasonaljersey >> tattoohead >> preferredposition2 >> strength >> shoetypecode >> birthdate >> preferredposition1 >> tattooleftleg >> skinmakeup >> ballcontrol >> phypos >> shotpower >> trait1 >> socklengthcode >> weight >> hashighqualityhead >> eyedetail >> tattoorightarm >> icontrait1 >> balance >> gender >> headassetid >> gkkicking >> defspe >> internationalrep >> shortpassing >> freekickaccuracy >> skillmoves >> faceposerpreset >> artificialkey >> usercaneditname >> avatarpomid >> finishingcode2 >> aggression >> acceleration >> paskic >> headingaccuracy >> iscustomized >> runningcode2 >> modifier >> gkhandling >> eyecolorcode >> jerseysleevelengthcode >> accessorycolourcode3 >> accessorycode1 >> playerjointeamdate >> headclasscode >> tattoofront >> nationality >> preferredfoot >> sideburnscode >> weakfootabilitytypecode >> jumping >> personality >> gkkickstyle >> stamina >> playerid >> accessorycolourcode4 >> gkpositioning >> headvariation >> skillmoveslikelihood >> trait2 >> shohan >> skintonecode >> shortstyle >> overallrating >> smallsidedshoetypecode >> emotion >> runstylecode >> muscularitycode >> skincomplexion >> jerseyfit >> accessorycode2 >> shoedesigncode >> shoecolorcode1 >> hairstylecode >> bodytypecode >> animpenaltiesstartposcode >> pacdiv >> defensiveawareness >> runningcode1 >> preferredposition4 >> volleys >> accessorycolourcode2 >> tattoorightleg >> facialhaircolorcode;
        break;
    }
}

FifaStoryModePlayer::FifaStoryModePlayer(FifaDataFile::Line &line) {
    internal.Read(line);
    m_gameId = 0;
}

bool FifaStoryModePlayer::IsMale() {
    return internal.gender == 0;
}
