#include "FifaKit.h"
#include "FifaDatabase.h"
#include <sstream>
#include <string>

void FifaKit::Internal::Read(FifaDataFile::Line & line) {
    switch (FifaDatabase::m_currentGameVersion) {
    case 11:
        line >> shortsnumberplacementcode >> teamcolorsecb >> shortsrenderingdetailmaptype >> jerseyfrontnumberplacementcode >> teamcolorprimg >> numberfonttype >> teamcolortertb >> jerseynamefonttype >> jerseynamelayouttype >> shortsnumbercolor >> jerseyshapestyle >> jerseybacknameplacementcode >> teamcolorprimr >> jerseynamecolorg >> teamcolorsecg >> teamcolortertr >> renderingmaterialtype >> teamcolorsecr >> jerseycollargeometrytype >> jerseynamecolorr >> numbercolor >> teamcolorprimb >> jerseyrenderingdetailmaptype >> shortsnumberfonttype >> jerseynamecolorb >> teamcolortertg >> jerseybacknamefontcase >> teamkittypetechid >> isinheritbasedetailmap >> teamkitid >> year >> teamtechid >> hasadvertisingkit >> dlc;
        break;
    case 12:
        line >> shortsnumberplacementcode >> teamcolorsecb >> shortsrenderingdetailmaptype >> jerseyfrontnumberplacementcode >> teamcolorprimg >> numberfonttype >> teamcolortertb >> jerseynamefonttype >> jerseynamelayouttype >> shortsnumbercolor >> jerseyshapestyle >> jerseybacknameplacementcode >> teamcolorprimr >> jerseynamecolorg >> teamcolorsecg >> teamcolortertr >> renderingmaterialtype >> teamcolorsecr >> jerseycollargeometrytype >> jerseynamecolorr >> numbercolor >> teamcolorprimb >> jerseyrenderingdetailmaptype >> shortsnumberfonttype >> jerseynamecolorb >> teamcolortertg >> jerseybacknamefontcase >> teamkittypetechid >> isinheritbasedetailmap >> teamkitid >> year >> teamtechid >> hasadvertisingkit >> dlc;
        break;
    case 13:
        line >> shortsnumberplacementcode >> teamcolorsecb >> shortsrenderingdetailmaptype >> jerseyfrontnumberplacementcode >> teamcolorprimg >> numberfonttype >> teamcolortertb >> jerseynamefonttype >> jerseynamelayouttype >> shortsnumbercolor >> jerseyshapestyle >> jerseybacknameplacementcode >> teamcolorprimr >> jerseynamecolorg >> teamcolorsecg >> teamcolortertr >> renderingmaterialtype >> teamcolorsecr >> jerseycollargeometrytype >> jerseynamecolorr >> numbercolor >> teamcolorprimb >> jerseyrenderingdetailmaptype >> shortsnumberfonttype >> jerseynamecolorb >> teamcolortertg >> jerseybacknamefontcase >> teamkittypetechid >> powid >> isinheritbasedetailmap >> islocked >> teamkitid >> year >> teamtechid >> hasadvertisingkit >> dlc;
        break;
    case 14:
        line >> shortsnumberplacementcode >> teamcolorsecb >> shortsrenderingdetailmaptype >> jerseyfrontnumberplacementcode >> teamcolorprimg >> numberfonttype >> teamcolortertb >> jerseynamefonttype >> jerseynamelayouttype >> shortsnumbercolor >> jerseyshapestyle >> jerseybacknameplacementcode >> teamcolorprimr >> jerseynamecolorg >> teamcolorsecg >> teamcolortertr >> renderingmaterialtype >> teamcolorsecr >> jerseycollargeometrytype >> jerseynamecolorr >> numbercolor >> teamcolorprimb >> jerseyrenderingdetailmaptype >> shortsnumberfonttype >> jerseynamecolorb >> teamcolortertg >> jerseybacknamefontcase >> teamkittypetechid >> powid >> isinheritbasedetailmap >> islocked >> teamkitid >> year >> teamtechid >> hasadvertisingkit >> dlc;
        break;
    case 15:
        line >> shortsnumberplacementcode >> teamcolorsecb >> shortsrenderingdetailmaptype >> jerseyfrontnumberplacementcode >> teamcolorprimg >> numberfonttype >> teamcolortertb >> jerseynamefonttype >> jerseynamelayouttype >> shortsnumbercolor >> jerseyshapestyle >> jerseybacknameplacementcode >> teamcolorprimr >> jerseynamecolorg >> teamcolorsecg >> teamcolortertr >> renderingmaterialtype >> teamcolorsecr >> jerseycollargeometrytype >> jerseynamecolorr >> numbercolor >> teamcolorprimb >> jerseyrenderingdetailmaptype >> shortsnumberfonttype >> jerseynamecolorb >> teamcolortertg >> jerseybacknamefontcase >> teamkittypetechid >> powid >> isinheritbasedetailmap >> islocked >> teamkitid >> year >> teamtechid >> hasadvertisingkit >> dlc >> jerseyfit;
        break;
    case 16:
        line >> shortsnumberplacementcode >> teamcolorsecb >> shortsrenderingdetailmaptype >> jerseyfrontnumberplacementcode >> teamcolorprimg >> numberfonttype >> teamcolortertb >> jerseynamefonttype >> jerseynamelayouttype >> shortsnumbercolor >> jerseyshapestyle >> jerseybacknameplacementcode >> teamcolorprimr >> jerseynamecolorg >> teamcolorsecg >> teamcolortertr >> renderingmaterialtype >> teamcolorsecr >> jerseycollargeometrytype >> jerseynamecolorr >> numbercolor >> teamcolorprimb >> jerseyrenderingdetailmaptype >> shortsnumberfonttype >> jerseynamecolorb >> teamcolortertg >> jerseybacknamefontcase >> teamkittypetechid >> powid >> isinheritbasedetailmap >> islocked >> teamkitid >> year >> teamtechid >> hasadvertisingkit >> dlc >> jerseyfit;
        break;
    case 17:
        line >> shortsnumberplacementcode >> shortsnumbercolorprimg >> teamcolorsecb >> shortsrenderingdetailmaptype >> jerseyfrontnumberplacementcode >> jerseynumbercolorsecr >> jerseynumbercolorprimr >> jerseynumbercolorprimg >> shortsnumbercolorsecb >> teamcolorprimg >> shortsnumbercolorterb >> shortsnumbercolorprimr >> numberfonttype >> teamcolortertb >> jerseynumbercolorterg >> shortsnumbercolorprimb >> jerseynamefonttype >> jerseynamelayouttype >> jerseynumbercolorterr >> jerseynumbercolorprimb >> jerseyshapestyle >> jerseybacknameplacementcode >> teamcolorprimr >> jerseynamecolorg >> teamcolorsecg >> shortsnumbercolorsecg >> teamcolortertr >> jerseynumbercolorsecg >> renderingmaterialtype >> shortsnumbercolorterr >> teamcolorsecr >> jerseycollargeometrytype >> shortsnumbercolorterg >> jerseynamecolorr >> teamcolorprimb >> jerseyrenderingdetailmaptype >> shortsnumberfonttype >> jerseynumbercolorsecb >> jerseynamecolorb >> jerseynumbercolorterb >> teamcolortertg >> shortsnumbercolorsecr >> jerseybacknamefontcase >> teamkittypetechid >> powid >> isinheritbasedetailmap >> islocked >> teamkitid >> year >> teamtechid >> isembargoed >> hasadvertisingkit >> dlc >> shortstyle >> jerseyfit;
        break;
    case 18:
        line >> shortsnumberplacementcode >> shortsnumbercolorprimg >> teamcolorsecb >> shortsrenderingdetailmaptype >> jerseyfrontnumberplacementcode >> jerseynumbercolorsecr >> jerseynumbercolorprimr >> jerseynumbercolorprimg >> shortsnumbercolorsecb >> teamcolorprimg >> shortsnumbercolorterb >> shortsnumbercolorprimr >> numberfonttype >> teamcolortertb >> jerseynumbercolorterg >> shortsnumbercolorprimb >> jerseynamefonttype >> jerseynamelayouttype >> jerseynumbercolorterr >> jerseynumbercolorprimb >> jerseyshapestyle >> jerseybacknameplacementcode >> teamcolorprimr >> jerseynamecolorg >> teamcolorsecg >> shortsnumbercolorsecg >> teamcolortertr >> jerseynumbercolorsecg >> renderingmaterialtype >> shortsnumbercolorterr >> teamcolorsecr >> jerseycollargeometrytype >> shortsnumbercolorterg >> jerseynamecolorr >> teamcolorprimb >> jerseyrenderingdetailmaptype >> shortsnumberfonttype >> jerseynumbercolorsecb >> jerseynamecolorb >> jerseynumbercolorterb >> teamcolortertg >> shortsnumbercolorsecr >> jerseybacknamefontcase >> teamkittypetechid >> powid >> isinheritbasedetailmap >> islocked >> teamkitid >> teamcolorprimpercent >> teamcolorsecpercent >> year >> teamtechid >> isembargoed >> hasadvertisingkit >> dlc >> teamcolortertpercent >> shortstyle >> jerseyfit;
        break;
    case 19:
        line >> shortsnumberplacementcode >> shortsnumbercolorprimg >> teamcolorsecb >> shortsrenderingdetailmaptype >> jerseyfrontnumberplacementcode >> jerseynumbercolorsecr >> jerseynumbercolorprimr >> jerseynumbercolorprimg >> shortsnumbercolorsecb >> teamcolorprimg >> shortsnumbercolorterb >> shortsnumbercolorprimr >> numberfonttype >> teamcolortertb >> jerseynumbercolorterg >> shortsnumbercolorprimb >> jerseynamefonttype >> jerseynamelayouttype >> jerseynumbercolorterr >> jerseynumbercolorprimb >> jerseyshapestyle >> jerseybacknameplacementcode >> teamcolorprimr >> jerseynamecolorg >> teamcolorsecg >> shortsnumbercolorsecg >> teamcolortertr >> jerseynumbercolorsecg >> renderingmaterialtype >> shortsnumbercolorterr >> teamcolorsecr >> jerseycollargeometrytype >> shortsnumbercolorterg >> jerseynamecolorr >> teamcolorprimb >> jerseyrenderingdetailmaptype >> shortsnumberfonttype >> jerseynumbercolorsecb >> jerseynamecolorb >> jerseynumbercolorterb >> teamcolortertg >> shortsnumbercolorsecr >> jerseybacknamefontcase >> chestbadge >> teamkittypetechid >> powid >> isinheritbasedetailmap >> islocked >> teamkitid >> teamcolorprimpercent >> jerseyrightsleevebadge >> teamcolorsecpercent >> jerseyleftsleevebadge >> year >> captainarmband >> teamtechid >> isembargoed >> hasadvertisingkit >> dlc >> teamcolortertpercent >> shortstyle >> jerseyfit;
        break;
    case 20:
        line >> shortsnumberplacementcode >> shortsnumbercolorprimg >> teamcolorsecb >> shortsrenderingdetailmaptype >> jerseyfrontnumberplacementcode >> jerseynumbercolorsecr >> jerseynumbercolorprimr >> jerseynumbercolorprimg >> shortsnumbercolorsecb >> teamcolorprimg >> shortsnumbercolorterb >> shortsnumbercolorprimr >> numberfonttype >> teamcolortertb >> jerseynumbercolorterg >> shortsnumbercolorprimb >> jerseynamefonttype >> jerseynamelayouttype >> jerseynumbercolorterr >> jerseynumbercolorprimb >> jerseyshapestyle >> jerseybacknameplacementcode >> teamcolorprimr >> jerseynamecolorg >> teamcolorsecg >> shortsnumbercolorsecg >> teamcolortertr >> jerseynumbercolorsecg >> renderingmaterialtype >> shortsnumbercolorterr >> teamcolorsecr >> jerseycollargeometrytype >> shortsnumbercolorterg >> jerseynamecolorr >> teamcolorprimb >> jerseyrenderingdetailmaptype >> shortsnumberfonttype >> jerseynumbercolorsecb >> jerseynamecolorb >> jerseynumbercolorterb >> teamcolortertg >> shortsnumbercolorsecr >> jerseybacknamefontcase >> chestbadge >> teamkittypetechid >> powid >> isinheritbasedetailmap >> islocked >> teamkitid >> teamcolorprimpercent >> jerseyrightsleevebadge >> teamcolorsecpercent >> jerseyleftsleevebadge >> year >> captainarmband >> teamtechid >> isembargoed >> hasadvertisingkit >> dlc >> teamcolortertpercent >> shortstyle >> jerseyfit;
        break;
    case 21:
        line >> chestbadge >> shortsnumberplacementcode >> shortsnumbercolorprimg >> teamcolorsecb >> shortsrenderingdetailmaptype >> jerseyfrontnumberplacementcode >> jerseynumbercolorsecr >> jerseynumbercolorprimr >> jerseynumbercolorprimg >> shortsnumbercolorsecb >> teamcolorprimg >> shortsnumbercolorterb >> shortsnumbercolorprimr >> numberfonttype >> teamcolortertb >> jerseynumbercolorterg >> shortsnumbercolorprimb >> jerseynamefonttype >> jerseynamelayouttype >> jerseynumbercolorterr >> jerseyrightsleevebadge >> jerseynumbercolorprimb >> jerseyshapestyle >> jerseybacknameplacementcode >> teamcolorprimr >> jerseynamecolorg >> jerseyleftsleevebadge >> teamcolorsecg >> shortsnumbercolorsecg >> teamcolortertr >> jerseynumbercolorsecg >> renderingmaterialtype >> shortsnumbercolorterr >> teamcolorsecr >> jerseycollargeometrytype >> shortsnumbercolorterg >> jerseynamecolorr >> teamcolorprimb >> jerseyrenderingdetailmaptype >> shortsnumberfonttype >> jerseynumbercolorsecb >> jerseynamecolorb >> jerseynumbercolorterb >> teamcolortertg >> shortsnumbercolorsecr >> jerseybacknamefontcase >> teamkittypetechid >> powid >> isinheritbasedetailmap >> islocked >> teamkitid >> teamcolorprimpercent >> teamcolorsecpercent >> year >> captainarmband >> teamtechid >> isembargoed >> hasadvertisingkit >> dlc >> teamcolortertpercent >> shortstyle >> jerseyfit;
        break;
    case 22:
        line >> chestbadge >> shortsnumberplacementcode >> shortsnumbercolorprimg >> teamcolorsecb >> shortsrenderingdetailmaptype >> jerseyfrontnumberplacementcode >> jerseynumbercolorsecr >> jerseynumbercolorprimr >> jerseynumbercolorprimg >> shortsnumbercolorsecb >> teamcolorprimg >> shortsnumbercolorterb >> shortsnumbercolorprimr >> numberfonttype >> teamcolortertb >> jerseynumbercolorterg >> shortsnumbercolorprimb >> jerseynamefonttype >> jerseynamelayouttype >> jerseynumbercolorterr >> jerseyrightsleevebadge >> jerseynumbercolorprimb >> jerseyshapestyle >> jerseybacknameplacementcode >> teamcolorprimr >> jerseynamecolorg >> jerseyleftsleevebadge >> teamcolorsecg >> shortsnumbercolorsecg >> teamcolortertr >> jerseynumbercolorsecg >> renderingmaterialtype >> shortsnumbercolorterr >> teamcolorsecr >> jerseycollargeometrytype >> shortsnumbercolorterg >> jerseynamecolorr >> teamcolorprimb >> jerseyrenderingdetailmaptype >> shortsnumberfonttype >> jerseynumbercolorsecb >> jerseynamecolorb >> jerseynumbercolorterb >> teamcolortertg >> shortsnumbercolorsecr >> jerseybacknamefontcase >> teamkittypetechid >> powid >> isinheritbasedetailmap >> islocked >> teamkitid >> teamcolorprimpercent >> teamcolorsecpercent >> year >> captainarmband >> teamtechid >> isembargoed >> hasadvertisingkit >> dlc >> teamcolortertpercent >> shortstyle >> jerseyfit;
        break;
    case 23:
        line >> chestbadge >> shortsnumberplacementcode >> shortsnumbercolorprimg >> teamcolorsecb >> shortsrenderingdetailmaptype >> jerseyfrontnumberplacementcode >> jerseynumbercolorsecr >> jerseynumbercolorprimr >> jerseynumbercolorprimg >> shortsnumbercolorsecb >> teamcolorprimg >> shortsnumbercolorterb >> shortsnumbercolorprimr >> numberfonttype >> teamcolortertb >> jerseynumbercolorterg >> shortsnumbercolorprimb >> jerseynamefonttype >> jerseynamelayouttype >> jerseynumbercolorterr >> jerseyrightsleevebadge >> jerseynumbercolorprimb >> jerseyshapestyle >> jerseybacknameplacementcode >> teamcolorprimr >> jerseynamecolorg >> jerseyleftsleevebadge >> teamcolorsecg >> shortsnumbercolorsecg >> teamcolortertr >> jerseynumbercolorsecg >> renderingmaterialtype >> shortsnumbercolorterr >> teamcolorsecr >> jerseycollargeometrytype >> shortsnumbercolorterg >> jerseynamecolorr >> teamcolorprimb >> jerseyrenderingdetailmaptype >> shortsnumberfonttype >> jerseynumbercolorsecb >> jerseynamecolorb >> jerseynumbercolorterb >> teamcolortertg >> shortsnumbercolorsecr >> jerseybacknamefontcase >> teamkittypetechid >> powid >> isinheritbasedetailmap >> islocked >> teamkitid >> teamcolorprimpercent >> teamcolorsecpercent >> year >> captainarmband >> teamtechid >> isembargoed >> hasadvertisingkit >> dlc >> teamcolortertpercent >> armbandtype >> shortstyle >> jerseyfit >> jerseyrestriction;
        break;
    }
}

FifaKit::FifaKit(FifaDataFile::Line & line) {
    internal.Read(line);
    m_team = nullptr;
}

unsigned int FifaKit::GetId() {
    return internal.teamkitid;
}
